
# Route page d'accueil 

accueil:
   path: /
   controller: App\Controller\ContactController::index

formulaire:
   path: /formulaire
   controller: App\Controller\ContactController::affichageForm

Mail:
   path: /mail
   controller: App\Controller\ContactController::envoiMail
